version: 0.2

env:
  parameter-store:
    GITHUB_TOKEN: "/continuous_apply/github_token"

phases:
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/components/deployer/scripts/ci/format.sh
      - ${CODEBUILD_SRC_DIR}/components/deployer/scripts/ci/validate.sh
      - ${CODEBUILD_SRC_DIR}/components/deployer/scripts/build.sh
